// Generated by CoffeeScript 1.6.3
(function() {
  window.User = {
    init: function() {
      return this.logInWithFacebook();
    },
    logInWithFacebook: function() {
      var _this = this;
      return $('#js-fb-login').on('click', function() {
        return _this.fbFlow();
      });
    },
    fbFlow: function() {
      var _this = this;
      return Parse.FacebookUtils.logIn(null, {
        success: function(user) {
          if (!user.existed()) {
            return console.log("User has signed up and logged in through facebook");
          } else {
            return console.log("User has logged in through facebook");
          }
        },
        error: function(user, error) {
          console.log("User Cancelled");
          return _this.logError(user, error);
        }
      });
    },
    logError: function(user, error) {
      return console.log("Error: " + error.code + " " + error.message);
    },
    createAndSaveUser: function() {
      var user,
        _this = this;
      user = new Parse.User();
      user.set("username", "my name");
      user.set("password", "my password");
      user.set("email", "my_email@example.com");
      return user.signUp(null, {
        success: function(user) {
          return console.log("Nice!");
        },
        error: function(user, error) {
          return logError(user, error);
        }
      });
    }
  };

}).call(this);
